### PR TITLE
(fix): Wrap page header in t function

### PR DESCRIPTION
**Pull request by NethmiRodrigo**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR wraps the page header title in the `t` function so that it can be translated. I had to add `Home` with the capital `H` to the translation files, as the key `home` doesn't get applied to the text.

## Screenshots

After fix:
Screenshot 2024-10-29 at 6 16 25 PM

Before fix:
Screenshot 2024-10-29 at 6 17 00 PM

### CODE REVIEW

**Comment by denniskigen** [comment]
I wouldn't expect to see changes to the non-`en` translation files made by hand - Transifex should take care of that.

**Comment by NethmiRodrigo** [comment]
@denniskigen yeah makes sense. I just added the same text that was there from `home`, should I remove it?

**Comment by denniskigen** [comment]
yeah, best to see what we get back from Transifex so we know if there's anything that should be fixed upstream.

**Comment by NethmiRodrigo** [comment]
Alrighty @denniskigen , done

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
