### PR TITLE
Added multiple roles/privileges needed for patient-search button to display

### PR DESCRIPTION
**Pull request by fatmali**
This PR fixes the blank page some users see when they log in. It is dependent on https://github.com/openmrs/openmrs-esm-api/pull/21

### CODE REVIEW

**Comment by fatmali** [comment]
This PR tries to solve the problem where some users might see a blank page after sign-in by adding the ability to allow multiple privileges and is reliant on https://github.com/openmrs/openmrs-esm-api/pull/21 
The problem that I came to realize later is for roles like superuser, the privileges array for this type of user is empty with the REST API. If we make this feature dependent on just privileges, superusers may not be able to see certain features. Also check the comments on the PR I mentioned above. cc @brandones  @jonathandick

**Comment by brandones** [comment]
> The problem that I came to realize later is for roles like superuser, the privileges array for this type of user is empty with the REST API.

That sounds like a REST API bug to me. @mseaton , what do you think?

**Comment by mseaton** [comment]
> > The problem that I came to realize later is for roles like superuser, the privileges array for this type of user is empty with the REST API.
> 
> That sounds like a REST API bug to me. @mseaton , what do you think?

This is probably not a REST bug, but I do not think that what is committed is the right solution - "System Developer" and "Super User" are not OpenMRS privileges, but rather "System Developer" is a role, and "Super User" is the name associated with the default user assigned to this role.

Off-hand without knowing the specifics of what led to this, what I'd say is that you should look at the Java API to see how privilege checking on the server side is done, and likely want to emulate that in a client-side API method.

If you look at https://github.com/openmrs/openmrs-core/blob/master/api/src/main/java/org/openmrs/User.java#L97

You'll see that checking whether a User has a particular privilege makes the following checks:

1. If the privilege is empty, return true
2. If the person is assigned to the Super User role (which is named "System Developer"), return true
3. If the user is assigned to a Role that has the privilege, return true
4. Otherwise, return false

**Comment by fatmali** [comment]
wow thanks for the insight @mseaton.

**Comment by brandones** [comment]
Yeah, that's very helpful. I think that approach could be fine, but I would really like it if we can make it very hard for implementers to make UI depend on the role. To what extent can we, technically, enforce that permissions are granted by privilege, not role?

**Comment by fatmali** [comment]
@brandones it's already enforced, if you look at https://github.com/openmrs/openmrs-esm-api/blob/28a13d94f0c59809e7caf278265b43af8f4894c8/src/shared-api-objects/current-user.ts#L37, it only checks for the privilege a user has. I think what we need to cater for is:

1. Add ability to check for multiple privileges, if any match, display the feature. (return true)
2. If the priviledge array is empty as in the case of super user, display the feature. (return true)
3. else don't display anything (return false)

We simple need to add the above logic into the `UserHasAccess` wrapper in esm-api and probably correct this PR to:
```
<UserHasAccessReact
            privileges={["View Patients"]}
          >
```

**Comment by mseaton** [comment]
I wouldn't necessarily assume that "Empty Privileges" = "System Developer".  There could just be users who have not been assigned to any roles and actually should not have any privileges too.

Since "System Developer" is a special-case type of role in the system, and the User.java class uses this in a method called "isSuperUser()", maybe we just ensure the REST representation of user contains a "superUser": true/false property in addition to the privileges set, and use this in the client side privilege checking.

**Comment by fatmali** [comment]
Good point @mseaton. For now, I'd suggest we check for the `Super User` role and only that role.

**Comment by brandones** [comment]
@fatmali Sounds like what you originally wrote, no? Can I resolve conflicts and merge the esm-api PR and this one, or is there something that needs to be changed?

**Comment by fatmali** [comment]
Submitted a new PR at https://github.com/openmrs/openmrs-esm-api/pull/30, if approved, we can close this.

**Comment by brandones** [comment]
openmrs/openmrs-esm-api#30 is in! Closing this.

**Pull request closed without merging**
